<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Whirl
 * @package     Whirl_Productrecommendation
 */
?>

<?php 
	$_productCollection = $this->getViewedProducts();
	$_helper = $this->helper('catalog/output');
?>

<?php 
	if (($_productCollection != null) && ($_productCollection->count() > 0)):
  	$_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
?>
	<div class="product-recommend-title">
		<h2><?php echo $this->getBlockTitle(); ?></h2>
	</div>
	
    <ul class="products-recommend grid--max-<?php echo $_columnCount; ?>-col">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
        	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
            <?php $_imgSize = 180; ?>
            	<img id="product-collection-image-<?php echo $_product->getId(); ?>"
                	src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
           	</a>
           	<div class="product-info">
	            <h2 class="product-name">
	            	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
	            </h2>
                
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->getAddToCartTitle($_product)) ?>" 
                        	class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span>
                        	<span><?php echo $this->getAddToCartTitle($_product); ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
			</div>
		</li>
	<?php endforeach ?>
	</ul>
	<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif;?>

